fd = open("pktnum", "w")
fd.close()
fd = open("siphurst", "w")
fd.close()
fd = open("diphurst", "w")
fd.close()

fd = open("Hsip", "w")
fd.close()
fd = open("Hdip", "w")
fd.close()
fd = open("Hdipsip", "w")
fd.close()
fd = open("pktnum", "w")
fd.close()
fd = open("1cmean", "w")
fd.close()
fd = open("1dvar", "w")
fd.close()
fd = open("2cmean", "w")
fd.close()
fd = open("2dvar", "w")
fd.close()
fd = open("3cmean", "w")
fd.close()
fd = open("3dvar", "w")
fd.close()
fd = open("4cmean", "w")
fd.close()
fd = open("4dvar", "w")
fd.close()
fd = open("5cmean", "w")
fd.close()
fd = open("5dvar", "w")
fd.close()
fd = open("6cmean", "w")
fd.close()
fd = open("6dvar", "w")
fd.close()
fd = open("7cmean", "w")
fd.close()
fd = open("7dvar", "w")
fd.close()
fd = open("8cmean", "w")
fd.close()
fd = open("8dvar", "w")
fd.close()
fd = open("10cmean", "w")
fd.close()
fd = open("10dvar", "w")
fd.close()